import type {Metadata} from 'next';
import {DEFAULT_BODY_CLASSNAME} from '@/components/Wrapper';

import '@gravity-ui/uikit/styles/fonts.css';
import '@gravity-ui/uikit/styles/styles.css';
import '../styles/globals.scss';
import StoreProvider from '@/components/StoreProvider/StoreProvider';
import React from 'react';

export const metadata: Metadata = {
    title: 'LogisticTable',
    description: 'Generated by create next app',
};

export default function RootLayout({children}: React.PropsWithChildren) {
    return (
        <html lang="en">
            <body className={DEFAULT_BODY_CLASSNAME}>
                <StoreProvider>{children}</StoreProvider>
            </body>
        </html>
    );
}
